#开发配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zjw.oa.entity
  mapperLocations: classpath:mapper/*.xml